#include "binx/cli/analysis_output.hpp"
#include <iomanip>
#include <sstream>
namespace binx { namespace { std::string esc(const std::string&s){std::string o;for(char c:s){if(c=='"')o+="\\\"";else if(c=='\\')o+="\\\\";else o+=c;}return o;} }
std::string format_strings(const std::vector<ExtractedString>&v,bool json){std::ostringstream o;if(json){o<<"{\"schema_version\":4,\"strings\":[";for(std::size_t i=0;i<v.size();++i){if(i)o<<",";o<<"{\"offset\":\"0x"<<std::hex<<v[i].offset<<"\",\"encoding\":\""<<string_encoding_name(v[i].encoding)<<"\",\"text\":\""<<esc(v[i].text)<<"\"}";}o<<"]}\n";return o.str();}o<<"STRINGS\n";for(auto&s:v)o<<"  0x"<<std::hex<<s.offset<<std::dec<<" ["<<string_encoding_name(s.encoding)<<"] "<<s.text<<"\n";return o.str();}
std::string format_hexdump(const std::vector<HexdumpLine>&v,bool json){std::ostringstream o;if(json){o<<"{\"schema_version\":4,\"lines\":[";for(std::size_t i=0;i<v.size();++i){if(i)o<<",";o<<"{\"offset\":\"0x"<<std::hex<<v[i].offset<<"\",\"bytes\":\"";for(auto b:v[i].bytes)o<<std::setw(2)<<std::setfill('0')<<unsigned(b);o<<"\"}";}o<<"]}\n";return o.str();}for(auto&l:v){o<<std::hex<<std::setw(8)<<std::setfill('0')<<l.offset<<"  ";for(std::size_t i=0;i<l.bytes.size();++i){if(i==8)o<<" ";o<<std::setw(2)<<unsigned(l.bytes[i])<<" ";}o<<std::setfill(' ')<<" |";for(auto b:l.bytes)o<<(b>=32&&b<=126?char(b):'.');o<<"|\n";}return o.str();}
std::string format_search(const std::vector<SearchMatch>&v,bool json){std::ostringstream o;if(json){o<<"{\"schema_version\":4,\"matches\":[";for(std::size_t i=0;i<v.size();++i){if(i)o<<",";o<<"{\"offset\":\"0x"<<std::hex<<v[i].offset<<"\",\"length\":"<<std::dec<<v[i].length<<"}";}o<<"]}\n";return o.str();}o<<"SEARCH MATCHES: "<<v.size()<<"\n";for(auto&m:v)o<<"  0x"<<std::hex<<m.offset<<std::dec<<" ("<<m.length<<" bytes)\n";return o.str();}
std::string format_regions(const std::vector<BinaryRegion>&v,bool json){std::ostringstream o;if(json){o<<"{\"schema_version\":4,\"regions\":[";for(std::size_t i=0;i<v.size();++i){if(i)o<<",";o<<"{\"offset\":\"0x"<<std::hex<<v[i].offset<<"\",\"size\":"<<std::dec<<v[i].size<<",\"kind\":\""<<region_kind_name(v[i].kind)<<"\"}";}o<<"]}\n";return o.str();}o<<"BINARY REGIONS\n";for(auto&r:v)o<<"  0x"<<std::hex<<r.offset<<std::dec<<" - "<<r.size<<" bytes  "<<region_kind_name(r.kind)<<"\n";return o.str();}
}
